/*
 Theme Name: Event4
 Theme URI: http://demo.newtemplate.net/event4/index.html
 Author: NewTemplate
 Author URI: https://themeforest.net/user/newtemplete
 Version: 0.1
 Description:  Event4 One Page HTML5 Theme comes out with tons of powerful features. Its modern, attractive and clean design.
 */

!function(i){"use strict";function a(e){var r=i(document).scrollTop();i("ul.ntNavbar li a").each(function(){var e=i(this),t=i(e.attr("href"));t.position().top<=r&&t.position().top+t.height()>r?(i("ul.ntNavbar li a").removeClass("active"),e.addClass("active")):e.removeClass("active")})}i(window).on("load",function(){i(".preloader").delay(100).fadeOut(500)}),i(window).on("scroll",function(){5<=i(window).scrollTop()?(i("header.ntHeader").addClass("ntStickyHeader fixed"),i(".ntStickyHeader.fixed").addClass("slideDown"),i(".cd-nav-trigger").addClass("fixed")):(i(".ntStickyHeader.fixed").removeClass("slideDown"),i("header.ntHeader").removeClass("ntStickyHeader fixed"),i(".cd-nav-trigger").removeClass("fixed"))}),i(".ntOurSpeakersItem").on("mouseenter mouseleave",function(){i(this).find(".caption").slideToggle(150),i(this).find(".overlay").slideToggle(150)}),i(document).on("scroll",a),i(".scroll").on("click",function(e){e.preventDefault(),i(document).off("scroll"),i("a").each(function(){i(this).removeClass("active")}),i(this).addClass("active");var t=this.hash,r=i(t);i("html, body").stop().animate({scrollTop:r.offset().top+2},1e3,"swing",function(){i(document).on("scroll",a)})}),i(".tnEventInfo .ntCaption:not(.tnSpeakerName)").hide(),i(".ntEvent.extend span").html("<i class='fa fa-angle-down'></i>"),i(".ntEvent.extend span").on("click",function(e){var t=i(this),r=t.parent().parent();"<i class='fa fa-angle-up'></i>"==t.html()?t.html("<i class='fa fa-angle-down'></i>"):t.html("<i class='fa fa-angle-up'></i>"),r.find(".tnEventInfo .ntCaption:not(.tnSpeakerName)").slideToggle(150)}),i(function(){i(".ntCounterNumber").countimator()});var n=function(e,t,r){"Disable"==e?i("#"+t).attr("disabled","disabled"):i("#"+t).removeAttr("disabled"),i("#"+t).val(r)};i("#registerForm").validate({errorElement:"span",rules:{reg_name:{required:!0},reg_jobtitle:{required:!0},reg_email:{required:!0},reg_company:{required:!0},reg_contact:{required:!0},reg_quantity:{required:!0},reg_attend:{required:!0}},messages:{reg_name:{required:"Required."},reg_jobtitle:{required:"Required."},reg_email:{required:"Required."},reg_company:{required:"Required."},reg_contact:{required:"Required."},reg_quantity:{required:"Required."},reg_attend:{required:"Required."}},submitHandler:function(e){var t,r,a;return n("Disable"),t="submit",a={complete:function(e){i("#registerForm").append("<div class='alert alert-success animated fadeInRight' id='success'><strong>Success!</strong> Your registration has been successfully submitted</div>"),setTimeout(function(){i("#success").addClass("animated fadeOutRight"),i("#success").removeClass("fadeInRight")},5e3),i("#registerForm")[0].reset(),n("Enabled",t,r)},error:function(e){var t=e.responseText;console.log(t)}},i("#"+"registerForm").ajaxSubmit(a),!1}})}(jQuery);